### 

POST http://localhost:1170/ctrl/login/request HTTP/1.1
content-type: application/json

{
    "phone": "{{$dotenv PHONE}}"
}

###

POST http://localhost:1170/ctrl/login/confirm HTTP/1.1
content-type: application/json

{
    "login_id": "{{$dotenv SESSION_ID}}",
    "code": "{{$dotenv CODE}}"
}


###

POST http://localhost:1170/ctrl/unfreeze HTTP/1.1
content-type: application/json

{{$dotenv SESSION_DATA}}
