GET http://localhost:1170/op/{{$dotenv SESSION_ID}}/check-self HTTP/1.1
content-type: application/json

###

GET http://localhost:1170/op/{{$dotenv SESSION_ID}}/freeze HTTP/1.1
content-type: application/json

###

POST http://localhost:1170/op/{{$dotenv SESSION_ID}}/chat/join-link HTTP/1.1
content-type: application/json

"https://t.me/bx666"
