GET http://localhost:1170/op/{{$dotenv SESSION_ID}}/self HTTP/1.1
content-type: application/json

###

GET http://localhost:1170/op/{{$dotenv SESSION_ID}}/freeze HTTP/1.1
content-type: application/json

### 

POST http://localhost:1170/op/{{$dotenv SESSION_ID}}/chat/resolve HTTP/1.1
content-type: application/json

MTGBG

###


GET http://localhost:1170/op/{{$dotenv SESSION_ID}}/chat/list HTTP/1.1
content-type: application/json


###

POST http://localhost:1170/op/{{$dotenv SESSION_ID}}/chat/join HTTP/1.1
content-type: application/json

{
    "ty": "Broadcast",
    "id": 1630168522,
    "access_hash": 6855744696224158010
}

###


POST http://localhost:1170/op/{{$dotenv SESSION_ID}}/chat/quit HTTP/1.1
content-type: application/json

{{$dotenv CHAT}}


###


POST http://localhost:1170/op/{{$dotenv SESSION_ID}}/info/channel HTTP/1.1
content-type: application/json

{{$dotenv CHAT}}


### 

GET http://localhost:1170/op/{{$dotenv SESSION_ID}}/chat/list HTTP/1.1

###


POST http://localhost:1170/op/{{$dotenv SESSION_ID}}/chat/iter-msg HTTP/1.1
content-type: application/json

{
    "chat": {{$dotenv CHAT}},
    "limit": 10
}

