[package]
name = "gram-pytools"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "gram_pytools"
crate-type = ["cdylib"]

[dependencies]
gram-core = { path = "../gram-core" }
image = "0.25.8"
pyo3.workspace = true
