[workspace]
members = ["gram-core", "gram-pytools", "gram-scraper"]
resolver = "3"

[patch.crates-io]
grammers-client = { git = "https://github.com/Lonami/grammers/" }
grammers-tl-types = { git = "https://github.com/Lonami/grammers/" }
