[package]
name = "gram"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
axum = { version = "0.8.4", features = ["ws"] }
grammers-client = { features = [
    "parse_invite_link",
    "serde",
], version = "0.7.0" }
serde = { version = "1.0.219", features = ["derive"] }
serde_bytes = "0.11.17"
sled = "0.34.7"
tokio = { version = "1.47.1", features = ["full", "tracing"] }
tracing = "0.1.41"
uuid = { version = "1.17.0", features = ["serde", "v4"] }

[patch.crates-io]
# grammers-client = { git = "https://github.com/RuofengX/grammers"}
grammers-client = { path = "../grammers/lib/grammers-client" }
