//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::types::UserFull;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "peer_people")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub updated_at: DateTimeWithTimeZone,
    pub user_scraper: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub full_info: Option<UserFull>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::peer_history::Entity")]
    PeerHistory,
    #[sea_orm(has_many = "super::peer_participant::Entity")]
    PeerParticipant,
    #[sea_orm(
        belongs_to = "super::user_scraper::Entity",
        from = "Column::UserScraper",
        to = "super::user_scraper::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserScraper,
}

impl Related<super::peer_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PeerHistory.def()
    }
}

impl Related<super::peer_participant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PeerParticipant.def()
    }
}

impl Related<super::user_scraper::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserScraper.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
