//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::types::ChannelFull;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "peer_channel")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub updated_at: DateTimeWithTimeZone,
    pub channel_id: i64,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub full_info: Option<ChannelFull>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::peer_history::Entity")]
    PeerHistory,
    #[sea_orm(has_many = "super::peer_participant::Entity")]
    PeerParticipant,
}

impl Related<super::peer_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PeerHistory.def()
    }
}

impl Related<super::peer_participant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PeerParticipant.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
