//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "peer_history")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub updated_at: DateTimeWithTimeZone,
    pub user_scraper: Uuid,
    pub people: Option<Uuid>,
    pub channel: Option<Uuid>,
    #[sea_orm(column_type = "JsonBinary")]
    pub message: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::peer_channel::Entity",
        from = "Column::Channel",
        to = "super::peer_channel::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PeerChannel,
    #[sea_orm(has_many = "super::peer_media::Entity")]
    PeerMedia,
    #[sea_orm(
        belongs_to = "super::peer_people::Entity",
        from = "Column::People",
        to = "super::peer_people::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PeerPeople,
    #[sea_orm(
        belongs_to = "super::user_scraper::Entity",
        from = "Column::UserScraper",
        to = "super::user_scraper::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserScraper,
}

impl Related<super::peer_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PeerChannel.def()
    }
}

impl Related<super::peer_media::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PeerMedia.def()
    }
}

impl Related<super::peer_people::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PeerPeople.def()
    }
}

impl Related<super::user_scraper::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserScraper.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
