//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "peer_participant")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub updated_at: DateTimeWithTimeZone,
    pub channel: Uuid,
    pub people: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::peer_channel::Entity",
        from = "Column::Channel",
        to = "super::peer_channel::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PeerChannel,
    #[sea_orm(
        belongs_to = "super::peer_people::Entity",
        from = "Column::People",
        to = "super::peer_people::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PeerPeople,
}

impl Related<super::peer_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PeerChannel.def()
    }
}

impl Related<super::peer_people::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PeerPeople.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
