//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

use crate::types::FrozenSession;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_scraper")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub updated_at: DateTimeWithTimeZone,
    pub confirm: Uuid,
    pub api_config: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub frozen_session: FrozenSession,
    pub in_use: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::global_api_config::Entity",
        from = "Column::ApiConfig",
        to = "super::global_api_config::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GlobalApiConfig,
    #[sea_orm(has_many = "super::peer_channel::Entity")]
    PeerChannel,
    #[sea_orm(has_many = "super::peer_file_part::Entity")]
    PeerFilePart,
    #[sea_orm(has_many = "super::peer_history::Entity")]
    PeerHistory,
    #[sea_orm(has_many = "super::peer_media::Entity")]
    PeerMedia,
    #[sea_orm(has_many = "super::peer_people::Entity")]
    PeerPeople,
    #[sea_orm(has_many = "super::user_chat::Entity")]
    UserChat,
    #[sea_orm(
        belongs_to = "super::user_confirm::Entity",
        from = "Column::Confirm",
        to = "super::user_confirm::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserConfirm,
}

impl Related<super::global_api_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GlobalApiConfig.def()
    }
}

impl Related<super::peer_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PeerChannel.def()
    }
}

impl Related<super::peer_file_part::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PeerFilePart.def()
    }
}

impl Related<super::peer_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PeerHistory.def()
    }
}

impl Related<super::peer_media::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PeerMedia.def()
    }
}

impl Related<super::peer_people::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PeerPeople.def()
    }
}

impl Related<super::user_chat::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserChat.def()
    }
}

impl Related<super::user_confirm::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserConfirm.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
