//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::types::PackedChat;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user_chat")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub updated_at: DateTimeWithTimeZone,
    pub user_scraper: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub username: Option<String>, // 存在无用户名的聊天, 用户没有设置即无用户名
    #[sea_orm(column_type = "JsonBinary")]
    pub packed_chat: PackedChat,
    pub joined: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_scraper::Entity",
        from = "Column::UserScraper",
        to = "super::user_scraper::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserScraper,
}

impl Related<super::user_scraper::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserScraper.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
