[package]
name = "gram-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
gram-core.path = "../gram-core"
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
teloxide = "0.17.0"
