use rusttype::Font;
use std::sync::LazyLock;

pub const FONTS: LazyLock<[Font; 59]> = LazyLock::new(|| {
    [
        // core noto fonts
        Font::try_from_bytes(include_bytes!("../fonts/DejaVuSans.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansDisplay-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansSC-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSans-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansMath-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoEmoji-Regular.ttf")).unwrap(),
        // extra noto fonts
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansKR-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansArmenian-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansJP-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansAvestan-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansBengali-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../noto-fonts/NotoSansBengaliUI-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansBrahmi-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansCarian-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansCherokee-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansCoptic-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansDeseret-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../noto-fonts/NotoSansDevanagari-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../noto-fonts/NotoSansDevanagariUI-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../noto-fonts/NotoSansEgyptianHieroglyphs-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansEthiopic-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansGeorgian-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../noto-fonts/NotoSansGlagolitic-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansGujarati-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../noto-fonts/NotoSansGujaratiUI-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansGurmukhi-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansHebrew-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../noto-fonts/NotoSansImperialAramaic-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansKayahLi-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansKaithi-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansKannada-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../noto-fonts/NotoSansKannadaUI-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../noto-fonts/NotoSansKharoshthi-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansKhmer-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansKhmerUI-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansLao-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansLaoUI-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansLycian-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansLydian-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../noto-fonts/NotoSansMalayalam-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../noto-fonts/NotoSansMalayalamUI-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansMono-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansNKo-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../noto-fonts/NotoSansOldSouthArabian-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../noto-fonts/NotoSansOldTurkic-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansOsmanya-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../noto-fonts/NotoSansPhoenician-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansShavian-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansSinhala-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansSymbols-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansTamil-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansTamilUI-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansTelugu-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansTeluguUI-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansThaana-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansThai-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansThaiUI-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansUgaritic-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../noto-fonts/NotoSansVai-Regular.ttf")).unwrap(),
    ]
});
